### PR TITLE
Added HijackThis O3 support

### PR DESCRIPTION
**Pull request by Slurppa**
- Added HijackThis O3 support
- Added RegistryExt class for extended operations related to registry
- Extended CLSID class functionality to take x64 & x86 registry views into account

### CODE REVIEW

**Comment by Slurppa** [comment]
I can but is there particular reason for targeting 4.6.2 specifically?

**Comment by iangcarroll** [comment]
Generally not a bad idea to stay on the latest versions, where compatibility permits. 4.6.2 in particular includes some fixes to how C# handles file names, which is great for driver paths prefixed by `/??/` and where file paths are longer than 260 characters.

4.6.1 actually causes CScan to stop working because it relies on those improvements.

**Comment by Slurppa** [comment]
Sounds plausible. I will make requested changes soon.

**Comment by iangcarroll** [comment]
Thanks for the help! :)

**Pull request merged**
